version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "tolicodes/tolicodes.com"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  convert:
    image: tolicodes/cf-kompose-plugin:latest
    stage: deploy
    working_directory: ${{CF_REPO_NAME}}
    environment:
      - CONVERT=true
      - FILE=docker-compose.production.yml

  deploy:
    title: Deploying App
    stage: deploy
    image: codefresh/kubectl
    working_directory: ${{CF_REPO_NAME}}
    commands:
      - kubectl config get-contexts
      - kubectl config use-context "${{KUBE_CONTEXT}}"
      - kubectl apply -f k8s
